# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.36
#
# Don't modify this file, modify the SWIG interface instead.
# This file is compatible with both classic and new-style classes.

import _bpp_font
import new
new_instancemethod = new.instancemethod
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


class Clonable(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Clonable, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Clonable, name)
    def __init__(self, *args, **kwargs): raise AttributeError, "No constructor defined"
    __repr__ = _swig_repr
    __swig_destroy__ = _bpp_font.delete_Clonable
    __del__ = lambda self : None;
    def clone(*args): return _bpp_font.Clonable_clone(*args)
Clonable_swigregister = _bpp_font.Clonable_swigregister
Clonable_swigregister(Clonable)

class Font(Clonable):
    __swig_setmethods__ = {}
    for _s in [Clonable]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Font, name, value)
    __swig_getmethods__ = {}
    for _s in [Clonable]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Font, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _bpp_font.new_Font(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _bpp_font.delete_Font
    __del__ = lambda self : None;
    def clone(*args): return _bpp_font.Font_clone(*args)
    def __eq__(*args): return _bpp_font.Font___eq__(*args)
    def getFamily(*args): return _bpp_font.Font_getFamily(*args)
    def getSeries(*args): return _bpp_font.Font_getSeries(*args)
    def getType(*args): return _bpp_font.Font_getType(*args)
    def getSize(*args): return _bpp_font.Font_getSize(*args)
    def setFamily(*args): return _bpp_font.Font_setFamily(*args)
    def setSeries(*args): return _bpp_font.Font_setSeries(*args)
    def setType(*args): return _bpp_font.Font_setType(*args)
    def setSize(*args): return _bpp_font.Font_setSize(*args)
    def toString(*args): return _bpp_font.Font_toString(*args)
Font_swigregister = _bpp_font.Font_swigregister
Font_swigregister(Font)



