# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.36
#
# Don't modify this file, modify the SWIG interface instead.
# This file is compatible with both classic and new-style classes.

import _bpp_atttools
import new
new_instancemethod = new.instancemethod
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


class AttributesTools(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, AttributesTools, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, AttributesTools, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _bpp_atttools.new_AttributesTools(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _bpp_atttools.delete_AttributesTools
    __del__ = lambda self : None;
    __swig_getmethods__["getVector"] = lambda x: _bpp_atttools.AttributesTools_getVector
    if _newclass:getVector = staticmethod(_bpp_atttools.AttributesTools_getVector)
    __swig_getmethods__["getAttributesMap"] = lambda x: _bpp_atttools.AttributesTools_getAttributesMap
    if _newclass:getAttributesMap = staticmethod(_bpp_atttools.AttributesTools_getAttributesMap)
    __swig_getmethods__["getAttributesMapFromFile"] = lambda x: _bpp_atttools.AttributesTools_getAttributesMapFromFile
    if _newclass:getAttributesMapFromFile = staticmethod(_bpp_atttools.AttributesTools_getAttributesMapFromFile)
    __swig_getmethods__["actualizeAttributesMap"] = lambda x: _bpp_atttools.AttributesTools_actualizeAttributesMap
    if _newclass:actualizeAttributesMap = staticmethod(_bpp_atttools.AttributesTools_actualizeAttributesMap)
    __swig_getmethods__["resolveVariables"] = lambda x: _bpp_atttools.AttributesTools_resolveVariables
    if _newclass:resolveVariables = staticmethod(_bpp_atttools.AttributesTools_resolveVariables)
    __swig_getmethods__["parseOptions"] = lambda x: _bpp_atttools.AttributesTools_parseOptions
    if _newclass:parseOptions = staticmethod(_bpp_atttools.AttributesTools_parseOptions)
AttributesTools_swigregister = _bpp_atttools.AttributesTools_swigregister
AttributesTools_swigregister(AttributesTools)
AttributesTools_getVector = _bpp_atttools.AttributesTools_getVector
AttributesTools_getAttributesMap = _bpp_atttools.AttributesTools_getAttributesMap
AttributesTools_getAttributesMapFromFile = _bpp_atttools.AttributesTools_getAttributesMapFromFile
AttributesTools_actualizeAttributesMap = _bpp_atttools.AttributesTools_actualizeAttributesMap
AttributesTools_resolveVariables = _bpp_atttools.AttributesTools_resolveVariables
AttributesTools_parseOptions = _bpp_atttools.AttributesTools_parseOptions



